### PR TITLE
more doxygen: warnings in fortran files starting with 'u'

### PR DESCRIPTION
**Pull request by edwardhartnett**
More doxygen.

Part of #246

### CODE REVIEW

**Comment by jbathegit** [comment]
Hey @edwardhartnett and @jack-woollen, I'm down to the last 2 pending PRs now, and it looks like there's some pending merge conflicts between this one and #302 - both have slightly different updates to uptdd, ups, usrtpl, and maybe others. 

Did you guys coordinate on these changes, and if so which PR should take precedence when there's a conflict?  It looks like they were both submitted the same day, but I'm guessing from the assigned number for this one that it may have been first into the chute?

Please reconcile and let me know - thanks!

**Comment by edwardhartnett** [comment]
Merge @jack-woollen 's first and then I will clear up conflicts in mine...

**Comment by jbathegit** [comment]
@edwardhartnett I'm ready to merge #302 as you requested, but you still have a block on it.  Please resolve - thanks!

**Comment by edwardhartnett** [comment]
OK, I've resolved conflicts.

Once this PR is merged, I will check if we have any more doxygen warnings.

**Comment by jbathegit** [comment]
Sounds good.  I've started working on this, and looking through the resulting doxygen I found a few other routines that we missed (makestab, strcln, etc.) so I'll get those fixed up as well and then you can run your check.

FYI I may not get this finished up until sometime tomorrow.  An impaired driver who slammed into our parked car back in December goes on trial today, and I've been subpoenaed as a witness so I'll be sitting in a courtroom for most of today.

**Comment by edwardhartnett** [comment]
@jbathegit good luck! Sounds like programming would be more fun!

**Comment by edwardhartnett** [comment]
How are we coming on getting this merged?

Once merged, I can try to turn on doxygen warnings...

**Comment by jbathegit** [comment]
I'll be pushing up a follow-on commit momentarily.  I also had to fill in a bunch of ??? in bufrlib.h.in, but I think it's good to go now.

However, as noted previously, and before you can do a warnings check, we'll still need some documentation added to src/moda_usrtmp.F and utils/readbp.f90.  @jack-woollen can you please help with those?

**Review by jack-woollen — DISMISSED** [review]

**Comment by jbathegit** [comment]
Almost done.  Still working on a few tweaks b/c doxygen isn't quite displaying things the right way...

**Comment by jbathegit** [comment]
Thanks for approving @jack-woollen but please give me a few more minutes before merging this.  Again, I'm trying to fix some weird doxygen results...

**Comment by jbathegit** [comment]
Once I get it straightened out I'll go ahead and do the merge, and then I did also see you more recent #309 and will look at that as well.  Again, I'm almost there...

**Comment by jbathegit** [comment]
OK I finally figured it out - for C codes, doxygen doesn't require docblocks in front of the corresponding prototypes in the .h file, because it automatically pulls all of the same documentation from the C code, including all of the variable descriptions.

Sorry it took me a while to figure out why this was working correctly for some C codes but not others.  It turned out it was b/c of inconsistent nomenclature (* pointer notation vs. [] array notation) for some of the variables between the prototype and the function declaration.  Thanks for your patience, and I'll get this merged now!

**Review by jbathegit — APPROVED** [review]

**Pull request merged**
