### PR TITLE
Add python read_long_string function

### LINKED ISSUE #226: Python wrapper for readlc function
Per an email request from jack.reeveseyre@noaa.gov, who works in NCEP/CPC:

When decoding ASCII data (e.g., station names) there is a mismatch between different python function results:
read_subset() cuts off the output at 8 characters;
print_subset() and dump_subset() produce the full name.
Do you know of a way to get the full result from the read_subset() call?

### PR DESCRIPTION
**Pull request by JackReevesEyre**
Fixes #226

Adds a python wrapper ("read_long_string" function) to the fortran function "readlc".

### CODE REVIEW

**Comment by JackReevesEyre** [comment]
I don't think I have permissions to add you as a reviewer @jbathegit. Maybe you're automatically assigned, and if not then this comment may do the job!

**Comment by jbathegit** [comment]
When I first ran the CI tests, I saw the following output:

```
/Users/runner/work/NCEPLIBS-bufr/NCEPLIBS-bufr/bufr/python/test/test.py:14: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  station_id = hdr[0].tostring()
/Users/runner/work/NCEPLIBS-bufr/NCEPLIBS-bufr/bufr/python/test/test.py:118: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  2.3407e+02,1.0000e+11,2.0008e+02],np.float)
/Users/runner/work/NCEPLIBS-bufr/NCEPLIBS-bufr/bufr/python/test/test.py:161: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  station_id = hdr[0].tostring()
/Users/runner/work/NCEPLIBS-bufr/NCEPLIBS-bufr/bufr/python/test/test.py:177: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  station_id = hdr[0].tostring()
```
This isn't from any of the changes you made to test.py; rather, I think the GitHub runner is probably now using a new version of Python that is being more nitpicky about this.  So I'll go ahead and push up a quick add-on commit to get rid of these warnings.

**Comment by jbathegit** [comment]
Or would you rather do this yourself, since it's your forked copy of the repository that would be directly affected(?)

**Review by jbathegit — DISMISSED** [review]

**Comment by jbathegit** [comment]
@JackReevesEyre are you OK with me pushing up a quick add-on commit to get rid of the above warnings, or would you like to do this yourself?  Just wanted to clear this with you since this is your forked repository.

On a separate note, I'm not sure why it's taking so long for the CI tests to run.  They've been queued up for several hours(?)

**Comment by JackReevesEyre** [comment]
Apologies - didn't see this message until now. Yes please go ahead and make the necessary changes.

**Comment by jbathegit** [comment]
No worries, and I'll try pushing it up in a few minutes.  Hopefully that will finally trigger the CI tests to run, since they still seem to be stuck in a queued status for some reason.  If that doesn't work then we may need to resort to a Plan B.

**Comment by jbathegit** [comment]
OK, that seemed to work, even though for some reason I had to resubmit 1 of the 7 tests because it failed initially not being able to do a cd (change directory) inside of the runner.  Anyway, all good now, and I'll get this merged into the baseline for the 11.7.1 release which should be NLT tomorrow.

Thanks again for your help!

**Review by jbathegit — APPROVED** [review]

**Comment by JackReevesEyre** [comment]
Great! Thank you!

**Pull request merged**
