### PR TITLE
addresses NCEPLIBS-bufr issues #19, #22, #23, #24, #25

### PR DESCRIPTION
**Pull request by jbathegit**

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Smaller PRs would be welcome...

I will take a look.

**Comment by jbathegit** [comment]
Understood, but in this case the majority of file changes are just to change from bufrlib.prm -> bufrlib.inc in every one of the Fortran source files, so those were always going to have to be done at the same time anyway (i.e. during a single commit), and you can likely quickly skim over those ;-)

**Comment by jbathegit** [comment]
@edwardhartnett if you want to see an example of what the new documentation looks like in a web browser, check out https://emc.ncep.noaa.gov/emc/pages/infrastructure/bufrlib_jeff/html/  Specifically, look at the files openbf.F and bvers.f, which are the two that I've really cleaned up so far.  But if you like how those look, and now that I'm more comfortable with the doxygen markdown, I should be able to get a lot more files done a lot more quickly for future pull requests.  Just let me know - thanks!

**Comment by edwardhartnett** [comment]
OK, thee's a lot going on in this PR. I'm going to submit some PRs with subsets of some of the easier changes, and that will clear up this PR so we can focus on the changes we need to focus on...

**Comment by edwardhartnett** [comment]
OK, I just put up 4 PRs with different parts of this PR. Let's get those reviewed and merged, and circle back around to this PR, which will be simplified...

**Comment by edwardhartnett** [comment]
Couple of notes:
* PR titles should describe the changes in the PR, not mention issue numbers.
* PR should always have a text description describing changes for reviewers.
* As you will notice, it's a lot easier to review a PR when it applies to only one issue.
* Using the text `Fixes #N` , when N is the issue number, is the preferred way to automatically close the issue, and noting that this PR contained the fix.
* Use the text `Part of #N` when you address part of an issue, and don't want to close it.

**Comment by jbathegit** [comment]
OK, I approved the pull requests, though I only saw 3 PRs, not 4 (did I miss one somewhere?)  So how should we proceed now with the bufrlib.prm -> bufrlib.inc changes?

**Pull request closed without merging**
