### PR TITLE
more testing for cpdxmm()

### LINKED ISSUE #33: Unit tests for src/copybf.f, src/copymg.f, src/copysb.f, src/cpbfdx.f, src/cpdxmm.f, src/cpymem.f, src/cpyupd.f
src/copybf.f, src/copymg.f, src/copysb.f, src/cpbfdx.f, src/cpdxmm.f, src/cpymem.f, src/cpyupd.f are all untested

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #445 
Fixes #33 

More testing for cpdxmm().

With this test, all codes mentioned in #33 have pretty good testing. A giant improvement from our starting point, where all of these functions were completely untested!

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@jbathegit and @jack-woollen this code seems to work fine, but how do I tell:

```
  ! Testing cpdxmm().
  open(unit = 11, file = 'testfiles/IN_2', form = 'UNFORMATTED', iostat = ios)
  if (ios .ne. 0) stop 5
  call openbf(11, 'IN', 11)
  call cpdxmm(11)
  call closbf(11)

```

After cpdxmm() has been called, what function(s) can I call to confirm that the embedded DX table has been correctly copied into memory?

**Review by jack-woollen — DISMISSED** [review]
In the test you commented out, the way its written, unit 12 needs to point to an ASCII version of the bufr tables. The file IN_1 is a bufr file with no bufr tables of any kind in it.

**Comment by edwardhartnett** [comment]
@jack-woollen thanks, but that does not answer my question. ;-)

How do I check that cpdxmm() has correctly copied to memory? What function can I call to learn the contents of that memory?

**Comment by jack-woollen** [comment]
My comment was about a different part of the code. Now that you mention cpdxmm I say two things. That test is not setup correctly because there's no memory file open. If you open a memory file (call ufbmem...) then its fairly complicated to check the result of calling cpdxmm. It would take some trial and error for me to work it out. I'm surprised cpdxmm doesn't check for an open memory file. Maybe Jeff should weigh in. @jbathegit

**Comment by jbathegit** [comment]
We could certainly add a failsafe check to cpdxmm, but for the record I'll point out that cpdxmm isn't a routine that was ever intended to be called directly by an application code.  In fact, the only place I know of that it's currently called from is within ufbmem itself, which by definition means that a file has already been opened to the internal memory arrays, and therefore such a failsafe check isn't really needed anyway.

So I'm struggling now to recall why we even included an im8b wrapper inside of cpdxmm in the first place.  I presume that's what Ed is trying to test in this PR, correct?  Jack, do you know of any application codes which call cpdxmm directly, and therefore why we even need an im8b wrapper inside of that routine?  If not, then I'd vote to just take it out of there.

**Comment by jack-woollen** [comment]
I think Ed's issue was about how to check to see if a test worked. Whether it needs to be tested or not is another issue I guess.

**Comment by edwardhartnett** [comment]
@jbathegit indeed it is the handling of the im8b wrapper that I am testing here.

I will add an issue for it's removal...

**Pull request closed without merging**
