### PR TITLE
update yaml file to use macos-11 in GitHub runner

### LINKED ISSUE #235: update yaml file to use macos-11 instead of soon-to-be-deprecated macos-10.15
macos-10.15 will no longer be available in the GitHub runner as of 12/1/2022.

See https://github.com/actions/runner-images/issues/5583 for more details.

### PR DESCRIPTION
**Pull request by jbathegit**
Fixes #235

### CODE REVIEW

**Comment by jbathegit** [comment]
I wanted to add @AlexanderRichert-NOAA as a reviewer as well, but for whatever reason GitHub couldn't find you in a search for potential "Reviewers"(?)

In any case, I'm a little confused here about why it's still expecting 4 build tests on macos-10.15.  Is there some other file besides `.github/workflows/main.yml` that needs to be modified here?  Or something else I missed?  I don't see anything else in the NCEPLIBS-bufr repository where there's still any reference to macos-10.15.

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Comment by jbathegit** [comment]
Thanks @Hang-Lei-NOAA 

Do you (or anyone else) have any idea why it's still expecting 4 build tests to be run with macos-10.15?  I couldn't find anywhere in any of the yaml files (or anywhere else) which would explain that.

In the past, there were a total of 14 CI tests in the GitHub runner, which have all passed here.  But now with this change it's expecting 4 additional tests (for a total of 18 CI tests) for some reason, and I haven't been able to figure out why?  Either way, it's blocking me from merging this PR.

**Comment by jbathegit** [comment]
@edwardhartnett @aerorahul @Hang-Lei-NOAA @AlexanderRichert-NOAA

Do any of you know the GitHub runner well enough to understand why it's still thinking it needs to run 4 tests on macos-10.15, even though (I think?) I've removed all of those requirements from the corresponding yaml file?  We need to get this figured out, because (as noted in #235), there will very soon only be macos-11 available in the runner.

Or, if you know of someone else who may know the answer to this, please feel free to add them to this chat thread - thanks!

**Comment by AlexanderRichert-NOAA** [comment]
Just poking around online, it seems that some users have had success with closing and reopening their pull request when there are these stuck "Expected" tests. For others it seems to be authentication related, though I don't know why these tests would be there in the first place...

**Comment by jbathegit** [comment]
> Just poking around online, it seems that some users have had success with closing and reopening their pull request when there are these stuck "Expected" tests. For others it seems to be authentication related, though I don't know why these tests would be there in the first place...

Thanks Alex.  I just tried closing and re-opening, and it's re-running all of the usual tests, but the 4 macos-10.15 ones still haven't gone away.

**Comment by AlexanderRichert-NOAA** [comment]
I think I found the issue. Can you get to this link? https://github.com/NOAA-EMC/NCEPLIBS-bufr/settings/branch_protection_rules/6113641
It looks like those specific tests are required under the branch protection rules (https://github.com/orgs/community/discussions/26698 ; https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule). If you go under repo Settings>Branches>Branch protection rules, you should be able to remove those tests.

**Comment by jbathegit** [comment]
Thanks Alex - much appreciated!

I went and edited those branch protection rules to change macos-10.15 to macos-11, and that seems to have done the trick!

**Pull request merged**
