### PR TITLE
updated README

### LINKED ISSUE #255: improve README
I think we can take a few iterations on the README to improve it a bit.

* We know the code authors, so lets list them. I have added @jack-woollen and @jbathegit . Who else wrote code?
* We would like to have a secondary code manager for this repo, so Jeff can take a vacation day occasionally. We could put me, or Hang, or Alex. That comes with a requirement that the secondary code manager maintain familiarity with the code, build, and CI system, so they can do an emergency release if necessary...
* I think we can reference some BUFR WMO docs, as we do the WMO GRIB docs from the GRIB repos.
* I don't think we should list supported compilers. In fact, all standard-conforming Fortran compiilers should work, with correct flags, and we do not officially support anything but Intel, right? So let's continue to support as many compilers as we think useful, and not specify them on the readme.
* Our build instructions should start with a GitHub release tarball, not a git clone.

Anything else anyone can think of?

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #255 

@jack-woollen and @jbathegit what other code authors should be listed, if any?

### CODE REVIEW

**Comment by jack-woollen** [comment]
Dennis Keyser and Stacy Bender if not authors,  have made many contributions to the bufrlib.

**Review by jack-woollen — COMMENTED** [review]
Besides J Ator and J  Woollen, Dennis Keyser and Stacey Bender could be mentioned.

**Review by jack-woollen — COMMENTED** [review]
One more "l" in Woollen!

**Review by jack-woollen — DISMISSED** [review]

**Comment by jbathegit** [comment]
Also Diane Stokes, Jeff Whiting, and Mark Shirey, if the idea is to list everyone who's ever made even a single contribution to any part of the library.

**Comment by jbathegit** [comment]
Almost forgot - also Ron McLaren who has provided substantial contributions to the Fortran/C interface.

**Comment by jbathegit** [comment]
I added a few minor tweaks:

- embed the link to the WMO manual in the introductory line
- add Diane Stokes as an author, and list Jack first since he's the original author and has contributed the most to the library over the years
- remove the information about multiple builds, since there is only one build effective with the merge of PR #250

**Review by jbathegit — APPROVED** [review]

**Comment by jbathegit** [comment]
OK, so this still needs the status checks to run even though it's just a change to README.md.  But the checks seem to have been stuck in limbo `Expected - Waiting for status to be reported` since yesterday.  How do we manually force them to run?

**Comment by jbathegit** [comment]
It may be b/c of the `paths-ignore: README.md` directive in all of the yaml scripts.  I see those are removed in PR #253, so I'll go ahead and merge that, then rebase it into this PR, then try again...

**Comment by jbathegit** [comment]
OK, that did the trick.  Now just need to wait for the checks to complete...

**Pull request merged**
