### PR TITLE
First pass at doxygen documentation

### LINKED ISSUE #14: README should be like other NCEPLIBS readmes...
README should conform to requirements here:
https://github.com/NOAA-EMC/NCEPLIBS/issues/120

Past code changes should go into a RELEASE_NOTES.md doc, if you want to keep them. 

On-going code changes should be listed in the release notes, not in the README.

### LINKED ISSUE #15: Add doxygen documentation
As described here:
https://github.com/NOAA-EMC/NCEPLIBS/issues/121

### PR DESCRIPTION
**Pull request by edwardhartnett**
First pass at doxygen. The results can be seen here: https://noaa-emc.github.io/NCEPLIBS-bufr/

Fixes #15
Fixes #14

### CODE REVIEW

**Comment by jbathegit** [comment]
@edwardhartnett - I really appreciate your help to get the Doxygen infrastructure in place (updated CMakeLists.txt, Doxygen.in, etc.).  This will be a big help going forward.  But as I noted previously, most of the BUFRLIB subprograms aren't intended to ever be directly called by a user from an application program.  Instead, BUFRLIB is a structured, tiered collection of subprograms, where users only ever need to call anywhere between 10-20 of them directly, and those codes in turn call other underlying subprograms, which in turn call other underlying subprograms, etc. throughout the rest of the library in order to accomplish the work requested by the user.  So I don't ever want users to have the impression that "all subprograms in this library are created equal", in the sense that they need to understand the interfaces to learn how to use all of them.  With over 300 different subprograms, that would quickly overwhelm anyone.

Is there any way we can just emphasize the important user-callable subprograms within Doxygen, so that the public-facing documentation only includes the details for those?  I can go through and mark up those specific subprograms (which are basically just the ones specifically described on the [BUFRLIB web site](https://emc.ncep.noaa.gov/emc/pages/infrastructure/bufrlib.php)), and I'm also willing to eventually go through and mark up all of the remaining 300+ subprograms, but that latter documentation only ever needs to be seen by myself and others who are actually maintaining the software, not by general users.  How can we make this delineation?

**Comment by edwardhartnett** [comment]
@jbathegit good questions!

The answer is, yes, of course we can indicate the important functions to the user. ;-)

The way to that is the file docs/user_guide.md. That is the main page of your documentation. As a simple case, if you put the following in, the functions would be automatically hyperlinked:

`some_func() - This func does something cool.
`

So in user_guide.md, you can do something like:

```
Here's some explanation, and here's a list of the 20 functions users should care about:
- func1() - some explanation
- func2() - some explanation
- func3() - some explanation
...
```

As long as func1() is defined somewhere in the doxygen build, then the name of the function will automatically get hyperlinked. See here for an example:

https://noaa-emc.github.io/NCEPLIBS-sp/

So let's get this PR merged, and then you can develop the main page that you want...

**Comment by jbathegit** [comment]
OK, that sounds good, and I'll go ahead and approve this review.  Then (though probably not until Monday at this point ;-), I'll do a git pull to update my clone on the WCOSS and start making the updates.  I'll work on this as quickly as I can in between other tasks, and I'm sure I'll have other questions as I go along, but for now this is definitely enough for me to get started.

**Comment by edwardhartnett** [comment]
BTW, annoyingly, I have not figured out how to get doxygen to automatically link when using upper-case. It always wants lower-case.

So even if you have a function:

`FUNCTION FUN1()
`
Doxygen wants you to refer to that as `fun1()` not `FUN1()`. 

;-(

**Review by jbathegit — APPROVED** [review]
OK and a good first step.  As agreed in #18 discussion, I will make further updates in subsequent commits.

**Comment by jbathegit** [comment]
Hmm, then that might become an added headache, since most of the Fortran subprogram names are written in upper-case in the source code.  I guess we'll have to figure this out as we go along.

**Review by jbathegit — APPROVED** [review]

**Comment by edwardhartnett** [comment]
What I meant about the upper/lower case thing only applies to when you refer to the function in the documentation.

That is, we don't have to change the FUNCTION FUN1() statement. But elsewhere in the documentation when we want to refer to FUN1() we must use lower case. So in other documentation we might have:

"See also function fun1()."

When we do that, Doxygen will automatically hyper-link to the documentation of fun1(). So that's handy.

But it doesn't work if we say:

"See also function FUN1()."

In that case, doxygen will not know to automatically link to fun1().

**Comment by jbathegit** [comment]
@edwardhartnett - I approved the changes per our recent discussion, but it doesn't look like they've been merged yet.  Are you waiting on me to do the merge?  If so, could you please let me know how to do this, as I've never done this within GitHub but rather have only ever done so in VLab.  So maybe I'm missing something here, but at any rate I just tried to do a git pull to refresh my clone on the WCOSS, and it didn't bring down any updates, which is why I'm guessing these recent changes haven't yet been merged into the develop branch.

**Comment by edwardhartnett** [comment]
Well it is telling me that a review is required.

So you have to hit the "Approve" button on your end. ;-)

**Review by jbathegit — APPROVED** [review]
OK and a good first step. As agreed in #18 discussion, I will make further updates in subsequent commits.   

approval

**Comment by jbathegit** [comment]
I already did that on Friday, in fact I did it twice as you can see if you scroll above through the thread history.  Maybe 3rd time will be the charm?

**Comment by edwardhartnett** [comment]
@kgerheiser can you see if you can approve this PR? We're having some troubles...

Of course it won't let me approve my own PR. ;-)

**Pull request merged**
