### PR TITLE
TEST PR: confirming new .workflows/*yml changes working as expected in GitHub runner

### PR DESCRIPTION
**Pull request by jbathegit**
see https://github.com/NOAA-EMC/NCEPLIBS-grib_util/issues/165 for more details of the impetus behind this change

### CODE REVIEW

**Comment by edwardhartnett** [comment]
Not sure what you are doing in this PR.

Code coverage is working in the develop branch currently, I just checked with a test PR.

**Comment by jbathegit** [comment]
This `r8wraps` branch is a working branch (nearly finished) to resolve #78.  But then when I saw your https://github.com/NOAA-EMC/NCEPLIBS-grib_util/issues/165 notes a couple of weeks ago, I tried to incorporate those same changes into main.yml and main_new.yml, and I submitted this test PR to make sure that it removed the "on push" tests, and that's when gcovr suddenly stopped working altogether!?

I realize your recent yml changes are working in the updated `develop` branch, so I realize this is ultimately on me and/or Jack to resolve, but this is really puzzling to me why gcovr suddenly has a problem parsing our revised test codes, as noted in #240.

**Comment by edwardhartnett** [comment]
Are you still having problems with gcovr? It is working in the develop branch. (Not for python - is that what you are trying to achieve?)

**Comment by jbathegit** [comment]
No, I'm not still having problems with gcovr.  That went away once I stopped trying to run it on the `../test` codes.

The issue I'm having now is with one of the modified test codes (the last one, in fact) failing on MacOS.  But it only fails on MacOS and nowhere else, and I don't have a MacOS platform of my own to run this on locally and hook up a debugging tool, so I have to resort to pushing up commits with temporary print statements and use the GitHub runner to try to sort out what's going on here.

**Comment by jbathegit** [comment]
Now, that this is working, I'll open a formal PR to merge this branch and close the underlying issue.

**Pull request closed without merging**
