### PR TITLE
Update moda* doxygen (1/2)

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
First of two batches of doxygen updates for src/moda* (9 files in this PR; 18 total).

Addresses https://github.com/NOAA-EMC/NCEPLIBS-bufr/issues/287

### CODE REVIEW

**Review by edwardhartnett — DISMISSED** [review]

**Comment by jbathegit** [comment]
@AlexanderRichert-NOAA in the future, could you please make a branch off of the main `NOAA-EMC:develop` branch, rather than forking your own clone of the entire repository in `AlexanderRichert-NOAA` and then making a branch off of that?  Having to work from your clone means it's a lot more work for me to reconcile your updates with all of the other updates being submitted by others in their PRs, because all of those are off of the main develop branch.  (Thanks!)

**Comment by jbathegit** [comment]
In the meantime, could you please update your forked clone of the repository to bring it up-to-date w.r.t. `NOAA-EMC:develop`, so that I can proceed with this, and with #292 as well?

**Comment by jbathegit** [comment]
> In the meantime, could you please update your forked clone of the repository to bring it up-to-date w.r.t. `NOAA-EMC:develop`, so that I can proceed with this, and with #292 as well?

Never mind this last part, as I figured a way around it for now ;-)

**Comment by AlexanderRichert-NOAA** [comment]
@jbathegit I usually update my fork's develop branch and pull updates first so this isn't generally an issue, but it sounds like you found the button for merging recent changes from develop :)

**Review by jbathegit — APPROVED** [review]

**Pull request merged**
