### PR TITLE
Add --output-on-failure to ctest

### PR DESCRIPTION
**Pull request by kgerheiser**
Related to #155 to show error message when tests fail.

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]

**Comment by jbathegit** [comment]
Interesting that the Python checks are now working.  As noted in #135, @edwardhartnett and I had problems getting these to work even before I tried to submit my PR #155.  I'm really puzzled here.

**Comment by jbathegit** [comment]
I guess I could go ahead and merge this PR back into `develop`, then re-baseline my `jba_noDA` branch and re-run the test and see what happens(?)

**Comment by aerorahul** [comment]
@jbathegit 
If the python tests fail at any point, please open an issue immediately.  
We added those tests to ensure they stay working, and not to be ignored in case they fail.

**Comment by jbathegit** [comment]
> @jbathegit
> If the python tests fail at any point, please open an issue immediately.
> We added those tests to ensure they stay working, and not to be ignored in case they fail.

@edwardhartnett did open an issue for this back in April when he first noticed this (see #135).  But it's still pending/unresolved.

**Comment by edwardhartnett** [comment]
I was just looking at all my issues and thinking that maybe zenhub will help... ;-)

Yes, python tests broke when I added code coverage. Not sure why. But that would have little to do with this issue, which is a cmake option...

**Pull request merged**
