### PR TITLE
changed README, moved history to separate file

### PR DESCRIPTION
**Pull request by edwardhartnett**
Part of #14 

Starting to edit readme.

What build instructions should be there?

### CODE REVIEW

**Comment by aerorahul** [comment]
@edwardhartnett 
Maybe the current `README.md` should be renamed/moved to `CHANGELOG.md`

**Comment by aerorahul** [comment]
Simple build and install instructions are:
```
git clone https://github.com/noaa-emc/nceplibs-bufr
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=./install -DENABLE_TESTS=ON nceplibs-bufr
make -j4
ctest
make install
```

Installation of the library and utilities will be under `./install`

**Review by jbathegit — APPROVED** [review]
OK by me.

**Comment by edwardhartnett** [comment]
Changes made based on @aerorahul comments, so re-review is required...

**Review by aerorahul — APPROVED** [review]
looks good.
thanks for fixing.

**Review by jbathegit — APPROVED** [review]

**Pull request merged**
