### PR TITLE
NCEPLIB-bufr Extension for Ioda-Converters Query Interface.

### PR DESCRIPTION
**Pull request by rmclaren**
This pull requests includes the minimal changes I will need to support the query interface for ioda converters (implemented in C++). Mostly its adds methods to expose some of the internal variables of NCEPLIB-bufr via the C interface. 

The most intrusive change I made was to make some of these variables targets. This was done for efficiency reasons, so that I could pass a pointer to the data arrays for message subsets, instead of first copying the data. Copying this data would result in unacceptable performance, so I needed the ability to point to the memory directly.

### CODE REVIEW

**Comment by edwardhartnett** [comment]
We need a GitHub issue to describe these changes.

Also the title for this PR is insufficient - what is "Feature/query cxx" supposed to indicate?

**Comment by jbathegit** [comment]
We'll also need one or more test codes which demonstrate the use of these new wrappers and validate them against sample test files.

**Comment by rmclaren** [comment]
I just wrote a long and meandering explanation as part of following issue:
https://github.com/NOAA-EMC/NCEPLIBS-bufr/issues/125

I'm not sure if there is a better way to link that issue to this PR... Please go ahead and link them.

**Comment by rmclaren** [comment]
I extended the test_c_interface.c file to cover the new c interface functions.

**Comment by jbathegit** [comment]
Thanks @rmclaren for the test codes.

I still don't fully understand why you need, as you put it, such "intrusive" access to the internal library arrays, but at the same time I don't necessarily have a problem with it if it's really needed, and so long as you're only reading out information and not also updating or otherwise changing anything in those arrays.  To that end, have you already looked at either of the following existing subroutines: [nemspecs](https://noaa-emc.github.io/NCEPLIBS-bufr/nemspecs_8f.html), [nemdefs](https://noaa-emc.github.io/NCEPLIBS-bufr/nemdefs_8f.html), just in case any of those would meet your needs?

Either way, and as you've probably noticed, we're kind of stuck at the moment from being able to merge **any** new updates into the develop branch, until we get some python CI issues sorted out.

**Comment by rmclaren** [comment]
@jbathegit Sorry Jeff, but the functions you mentioned are not helpful...

**Comment by jbathegit** [comment]
This is the next one in the backlog ;-)  I'm rerunning the CI tests now.

While it's not ideal that anyone calling get_inv_f or get_val_f is going to end up with pointers enabling write access to the internal INV and VAL arrays, I get it that it's a performance drag to otherwise have to copy all of that data, so I'm inclined to OK this once the tests pass, unless @jack-woollen has any additional concerns(?)

**Comment by jack-woollen** [comment]
Seems to me like a reasonable way to directly access those data from outside FORTRAN.

**Review by jbathegit — APPROVED** [review]

**Pull request merged**
