### PR TITLE
add links to prior versions of documentation

### LINKED ISSUE #183: add support for multiple versions of the documentation
See https://github.com/NOAA-EMC/NCEPLIBS-g2c/issues/126

### PR DESCRIPTION
**Pull request by jbathegit**
Fixes #183

### CODE REVIEW

**Comment by jbathegit** [comment]
@edwardhartnett could you please take a look at this when you get a chance, and please let me know whether you agree that this is a satisfactory solution to this issue?

**Comment by edwardhartnett** [comment]
Well that is not exactly what I meant.

Take a look at the g2c project documentation. Notice that at the top it says:

> 
> Documentation for Previous Versions of NCEPLIBS-g2c
> [NCEPLIBS-g2c Version 1.6.4](https://noaa-emc.github.io/NCEPLIBS-g2c/ver-1.6.4/index.html)

The way this was done was to add a subdirectory called ver-1.6.4 to the gh-pages branch. Instead of deleting the documentation on gh-pages when updating the new release, move the files into a subdirectory. THen, in user_guide.md, add this:

```
## Documentation for Previous Versions of NCEPLIBS-g2c

* [NCEPLIBS-g2c Version 1.6.4](ver-1.6.4/index.html)


```

This way all the documentation for a previous version is availabe.

**Comment by jbathegit** [comment]
I hear what you're saying Ed, but as I noted in the discussion for #183, the documentation for the previous versions **is** already available in new subdirectories off of the `gh-pages` branch, and users just need to follow the link to the Releases page and select the version they want that way.  As I noted, I was trying to avoid having to change `docs/user_guide.md` every time we release a new version.

That said, it's not that big a deal to me, so if you really prefer it your way then I'll go ahead and push up another commit according to how you have it for the NCEPLIBS-g2c library.

**Comment by jbathegit** [comment]
OK, how's this look?

**Comment by jbathegit** [comment]
I just realized I could simplify even further by using relative URLs, like in your above example.

**Comment by edwardhartnett** [comment]
OK, looks good...

**Comment by jbathegit** [comment]
Cool, thanks Ed!

In that case, could you please formally approve this PR so I can merge it? ;-)

**Review by edwardhartnett — APPROVED** [review]

**Pull request merged**
