### PR TITLE
modified Fortran variable declarations for compatibility with GNU v10+

### LINKED ISSUE #81: Possible Standards Violation in moda_mstabs.F
All,

Recently I tried to compile the NCEP_bufr library in GEOS which led to an [issue with compiling with GCC 10](https://github.com/GEOS-ESM/NCEP_Shared/issues/16) with `moda_mstabs.F`:
```
[  0%] Building Fortran object src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/moda_mstabs.F.o
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:39:44:

   39 |    CHARACTER*4, BIND(C) :: CBBW(MXMTBB)
      |                                            1
Error: BIND(C) Variable ‘cbbw’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:42:48:

   42 |    CHARACTER*120, BIND(C) :: CBELEM(MXMTBB)
      |                                                1
Error: BIND(C) Variable ‘cbelem’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:41:46:

   41 |    CHARACTER*8, BIND(C) :: CBMNEM(MXMTBB)
      |                                              1
Error: BIND(C) Variable ‘cbmnem’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:37:45:

   37 |    CHARACTER*4, BIND(C) :: CBSCL(MXMTBB)
      |                                             1
Error: BIND(C) Variable ‘cbscl’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:38:47:

   38 |    CHARACTER*12, BIND(C) :: CBSREF(MXMTBB)
      |                                               1
Error: BIND(C) Variable ‘cbsref’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:40:47:

   40 |    CHARACTER*14, BIND(C) :: CBUNIT(MXMTBB)
      |                                               1
Error: BIND(C) Variable ‘cbunit’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:45:46:

   45 |    CHARACTER*8, BIND(C) :: CDMNEM(MXMTBD)
      |                                              1
Error: BIND(C) Variable ‘cdmnem’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:44:47:

   44 |    CHARACTER*120, BIND(C) :: CDSEQ(MXMTBD)
      |                                               1
Error: BIND(C) Variable ‘cdseq’ at (1) must have length one
src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/build.make:1903: recipe for target 'src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/moda_mstabs.F.o' failed
make[3]: *** [src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/moda_mstabs.F.o] Error 1
CMakeFiles/Makefile2:10370: recipe for target 'src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/all' failed
make[2]: *** [src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/all] Error 2
CMakeFiles/Makefile2:10377: recipe for target 'src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/rule' failed
make[1]: *** [src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/rule] Error 2
Makefile:2554: recipe for target 'NCEP_bufr_r4i4' failed
make: *** [NCEP_bufr_r4i4] Error 2
```

Note: our version of this file is exactly the same as the one here. 

Now, we are not compiling with `DYNAMIC_ALLOCATION` (for good or ill). Intel seems to not care (at least how we call Intel), but a workaround for now with GNU will be turn that on, but I can't by fiat do that for all compilers since I have no idea how to test the effects (we know GNU can't run our ADAS at the moment).

I'm going to ping @tclune who has the Fortran knowledge to know why this is an issue.

### PR DESCRIPTION
**Pull request by jbathegit**
Fixes #81 

I modified several internal declarations as discussed in the ticket, and these test successfully on our current platforms, but I have no access to a GNU v10+ compiler to verify them with.   So could I please ask @mathomp4 and @tclune to pull these updates and test them out yourselves on your own systems to verify they're now compatible with that compiler, before I/we merge this new branch into develop?

The changes are just to declarations (no changes to functionality), and the subprograms and code lines involved are already well-covered by the existing test suite, so no new test cases are needed.

### CODE REVIEW

**Comment by mathomp4** [comment]
@jbathegit Well, as an "easy" test, I copied the `moda_mstabs.F` from your branch into our code base. I then disabled the `-DDYNAMIC_ALLOCATION` workaround I've been doing to let things build:
```cmake
if (CMAKE_Fortran_COMPILER_ID MATCHES "GNU")
   target_compile_definitions (${this} PRIVATE $<$<COMPILE_LANGUAGE:Fortran>:DYNAMIC_ALLOCATION>)
endif ()
```
And...it built!

I didn't try your full new branch as it seems to be pretty different in terms of new files, CMake, etc.

**Comment by jbathegit** [comment]
Thanks @mathomp4 for confirming!  That's helpful, even if you haven't had a chance to run a full test of the entire updated library.  But is there any possibility you could do so, sometime in the not-too-distant future?  I'd really like for someone with access to a GNU v10+ compiler to test and verify the full contents of this new branch before I consider merging it into the baseline (develop) branch.  And I figured who better to ask than the person who found and reported the issue in the first place! ;-)

Please let me know - thanks!

**Comment by edwardhartnett** [comment]
@jbathegit see #93  - we need to test with gfortran 10 ourselves...

**Comment by jbathegit** [comment]
OK, if anyone on our end can help with this, please let me know.

**Comment by kgerheiser** [comment]
I am adding an action to use GCC-9 and GCC-10

**Comment by jbathegit** [comment]
Part of #77 

OK, we're all set now with full testing of all memory builds (static and dynamic) on all platforms, including GNU v10+

Now I just one of you to kindly review and approve these changes so that I can merge them back into the develop branch ;-)

**Review by aerorahul — APPROVED** [review]
CMake changes look good.
I have not reviewed the fortran changes carefully, but they look good to me.

**Pull request merged**
