### PR TITLE
eliminate duplication of replication sequences within stseq function

### LINKED ISSUE #612: look into eliminating RPSEQ### duplication in stseq function
Currently, when the stseq function recursively runs to store internal table information for a standard Table D descriptor, it doesn't keep track of which RPSEQ### sequences it has already generated, which means duplication can occur such as the following snippet from a run of the debufr utility on test/testfiles/IN_4:

```
| MSTTB001 | GSRADSEQ  222000  236000  "RPSEQ002"185  GCLONG  GNAP             |
| MSTTB001 | "RPSEQ003"36  222000  237000  GCLONG  GNAP  MDPC  "RPSEQ004"36    |
| MSTTB001 | 222000  237000  GCLONG  GNAP  MDPC  "RPSEQ005"36  222000  237000  |
| MSTTB001 | GCLONG  GNAP  MDPC  "RPSEQ006"36  222000  237000  GCLONG  GNAP    |
| MSTTB001 | MDPC  "RPSEQ007"36  224000  237000  GCLONG  GNAP  FOST            |
| MSTTB001 | "RPSEQ008"36  224000  237000  GCLONG  GNAP  FOST  "RPSEQ009"36    |
|          |                                                                   |
| GSRADSEQ | SIDENSEQ  NPPR  NPPC  LSQL  SAZA  SOZA  HITE  "CLFRASEQ"12        |
| GSRADSEQ | "RPSEQ001"2  "CSRADSEQ"12                                         |
|          |                                                                   |
| SIDENSEQ | SIDGRSEQ  YYMMDD  HHMMSS  LTLONH                                  |
|          |                                                                   |
| SIDGRSEQ | SAID  GCLONG  SCLF  SSNX  SSNY                                    |
|          |                                                                   |
| YYMMDD   | YEAR  MNTH  DAYS                                                  |
|          |                                                                   |
| HHMMSS   | HOUR  MINU  SECO                                                  |
|          |                                                                   |
| LTLONH   | CLATH  CLONH                                                      |
|          |                                                                   |
| CLFRASEQ | SCCF  SCBW  CLDMNT  NCLDMNT  CLTP                                 |
|          |                                                                   |
| RPSEQ001 | SIDP  IMHC  PRLC  PRLC  REHU                                      |
|          |                                                                   |
| CSRADSEQ | SIDP  RDTP  RDCM  SCCF  SCBW  SPRD  RDNE  TMBRST                  |
|          |                                                                   |
| RPSEQ002 | DPRI                                                              |
|          |                                                                   |
| RPSEQ003 | PCCF                                                              |
|          |                                                                   |
| RPSEQ004 | PCCF                                                              |
|          |                                                                   |
| RPSEQ005 | PCCF                                                              |
|          |                                                                   |
| RPSEQ006 | PCCF                                                              |
|          |                                                                   |
| RPSEQ007 | PCCF                                                              |
|          |                                                                   |
| RPSEQ008 | 224255                                                            |
|          |                                                                   |
| RPSEQ009 | 224255                                                            |
```

So, for example, it might be useful to be able to replace the last 14 lines above with just:
```
|          |                                                                   |
| RPSEQ003 | PCCF                                                              |
|          |                                                                   |
| RPSEQ004 | 224255                                                            |
```
and then replace all occurrences of `RPSEQ00[3-7]` and `RPSEQ00[89]` with, respectively, `RPSEQ003` and `RPSEQ004` in the prior `MSTTB001` definition.  To do this would likely just require stseq to start keeping its own internal sequence cache between recursive calls, and then before each instance where it currently calls igettdi and stseq to store a new RPSEQxxx sequence with xxx = irepct+1, it first checks its internal cache of existing RPSEQyyy sequences where yyy = 0, 1, 2, ..., irepct to see whether an identical sequence has already been stored, and if so just re-uses that same RPSEQyyy sequence instead of calling igettdi and stseq to store a new one.

Off the top of my head, I'm thinking this cache of already-stored RPSEQyyy mnemonics and corresponding rpidn (i.e. FXY) numbers could be maintained in a separate new C function that's only ever called from within stseq.  Of course, we'd also have to include a way to reset the cache back to yyy = 0 whenever stseq itself is called with irepct = 0.

### PR DESCRIPTION
**Pull request by jbathegit**
Fixes #612 

Also eliminates dlloctbf_c binding which is no longer needed.

### CODE REVIEW

**Comment by jbathegit** [comment]
Hey @jack-woollen @edwardhartnett @AlexanderRichert-NOAA would any of you possibly have some time during the next couple of days to take a look at this?

(Thanks! :-)

**Review by AlexanderRichert-NOAA — APPROVED** [review]
How easy would it be to add remaining code coverage for stseq.c? I don't think you're technically adding new untested lines of code, but there are some untested lines that got shuffled around a bit, if I'm reading the diff correctly. Otherwise looks good.

**Review by jack-woollen — APPROVED** [review]

**Comment by jbathegit** [comment]
> How easy would it be to add remaining code coverage for stseq.c? I don't think you're technically adding new untested lines of code, but there are some untested lines that got shuffled around a bit, if I'm reading the diff correctly. Otherwise looks good.

Thanks Alex and Jack for your replies!

Alex, you're correct that I'm not adding any untested lines with this PR, and that all of the untested lines in stseq() are ones that previously existed.  But many of those aren't easy to test, either because they're hard to simulate (e.g. if a malloc fails, or if pktdd() somehow encounters a corrupt counter value) or because I've never actually seen any cases of NWP centers generating sample data with some of these more esoteric BUFR features (e.g. substituted values, replaced/retained values) even though they are theoretically possible according to the WMO regulations.

If and when any of that changes, then I'll certainly be more than willing to add new test cases.  But for now at least the testing coverage is as complete as I can manage for stseq().

**Comment by edwardhartnett** [comment]
Indeed in Fortan and C it is not usual to test for such error conditions. There's no reasonable way to make malloc fail, but you should certainly have code to deal with a malloc failure. So that code will be impossible to reach in testing.

In other languages, like Python, there is a concept of "mocking" which allows us to easily reach 100% test coverage. But there's no easy way to do that in Fortran/C, so I'm happy to achieve something over 80% with Fortran/C code. And I believe NCEPLIBS-bufr is well into the 90s now...

**Pull request merged**
