### PR TITLE
Update doxygen for #279

### LINKED ISSUE #279: doxygen changes for moda_comprs.F moda_comprx.F moda_dscach.F moda_h4wlc.F moda_idrdm.F moda_ival.F  moda_ivttmp.F moda_lushr.F moda_mgwa.F  moda_mgwb.F  moda_msgcwd.F
Please update the doxygen for moda_comprs.F moda_comprx.F moda_dscach.F moda_h4wlc.F moda_idrdm.F moda_ival.F  moda_ivttmp.F moda_lushr.F moda_mgwa.F  moda_mgwb.F  moda_msgcwd.F.

### PR DESCRIPTION
**Pull request by AlexanderRichert-NOAA**
More doxygen.

Fixes #279

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@jack-woollen and @jbathegit there are lots of ??? in this PR to fill in...

**Review by edwardhartnett — DISMISSED** [review]

**Comment by jbathegit** [comment]
> @jack-woollen and @jbathegit there are lots of ??? in this PR to fill in...

I know, and I've already started working on this one.  I've been working on all of the PRs in oldest to newest order, but there have been a lot of them, and it takes time to carefully review each one (including the resulting doxygen via a web browser) and fill in any missing details or other items.

Please understand that I am working on this, and I really do appreciate all of the help from all of you, but you're just generating PRs faster than I can keep up with all of them.

**Comment by edwardhartnett** [comment]
The good news is, once these PRs all get through, I think we will have no more doxygen warnings. That will be great! Probably by early next week, at this rate.

Take as much time as you need on each PR. We package them separately so that you can review them one at a time and not spend all day reviewing code. It's OK if one or two a day get merged.

**Review by jbathegit — APPROVED** [review]

**Comment by jbathegit** [comment]
OK, this is all done now except for moda_ivttmp.F  I don't know what those variables are, so @jack-woollen could you please go and fill in the ??? in that module whenever you have some time?

**Pull request merged**
